server:
  port: 9090

spring:
  application:
    name: msvc-course

  datasource: #configuracion para base la base de datos
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursesDb
    username: postgres
    password: 12345

  jpa: #JPA
    hibernate:
      ddl-auto: create #Cuando se levante que genere las tablas
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#Configuracion para que eureka lo reconozca
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
