#Es la configuracion interna del microservicio pero para la configuracion
#Esto estaba en application.yml de student, he eliminado aqui el config y en application he dejado solo spring application
server:
  port: 8090

spring:
  application:
    name: msvc-student

  datasource: #configuracion para base la base de datos
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentDb
    username: root
    password: sasa

  jpa: #JPA
    hibernate:
      ddl-auto: create #Cuando se levante que genere las tablas
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#Configuracion para que eureka lo reconozca
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka